use_frameworks!

platform :ios, '8.0'

target 'KKIOSRe_Example' do
  pod 'KKIOSRe', :path => '../'

  target 'KKIOSRe_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
